### ISSUE TITLE
Add store finder option

### ISSUE THREAD

**Issue by boblennes** [LaGrangeMtl/WhatsNearby#2]
See my fork in case you'd like to add in to your library.
Thanks!

**Comment by MaximeDesRoches** [comment]
Could you make a pull request with your code formatted like my code (hard tabs), so we don't have a complete rewrite with spaces tabs ?

**Comment by MaximeDesRoches** [comment]
I also have an improved version on the way, where you can pass custom places to the map, so you may want to wait a bit before making the pull request.

**Comment by leepeterson** [comment]
@MaximeDesRoches Any progress made on the custom places? Would like to pass in a JSON array of places composed of locations created in a CMS.

**Comment by MaximeDesRoches** [comment]
Hey, I just updated the repo with an enhanced version of WhatsNearby. The new version is rewritten in ES6 and has the added ability to show custom markers:

    wn = mapNode.whatsnearby({
		backgroundColor: '#f0f0f0',
		placeMainMarker: false,
		streetViewControl: false,
	}).data('whatsnearby');

	const OverlayMap = new CustomOverlay({ map: wn.map }, markersList, null, onClickMarker);

Tell me if you need any more help :)

**Comment by boblennes** [comment]
I submitted a pull request to the new version to find by store name.

**Comment by MaximeDesRoches** [comment]
I just merged it in the master branch, thanks.
