### ISSUE TITLE
 infoBoxOptions: {}

### ISSUE THREAD

**Issue by weilinzung** [LaGrangeMtl/WhatsNearby#4]
How are these options code looks like inside of the bucket?  do you have any example?
 infoBoxOptions: {}

And also when I click my marker, there is no info box open, do I miss anything?

thanks.

**Comment by MaximeDesRoches** [comment]
The InfoBoxOptions is directly feeded to the InfoBox Class from Google Maps Utils (https://github.com/googlemaps/v3-utility-library/blob/master/infobox/src/infobox.js). If you include this library, you will be able to modify the appearance of the infowindow.

**Comment by weilinzung** [comment]
ok thanks. 

The only thing is that my address locaiton when I click the marker, that doesn't come out the infobox of my place info.

One more question, for the mainMarkerIcon, I am using svg image, how can I resize it by CSS? or need to done by the JS? thanks!
